stages:
  prepare:
    cmd: python3 extract-characters/main_run.py ../steles/detected/ ../steles/detected/
      32 32
    deps:
    - extract-characters/load_data.py
    - extract-characters/main_run.py
    params:
    - prepare.height
    - prepare.width
    outs:
    - extract-characters/imgs
  cluster:
    cmd: python3 extract-characters/char_cluster.py 
    deps:
    - extract-characters/imgs
    - extract-characters/char_cluster.py
    outs:
    - extract-characters/clusters.json
