stages:
  load:
    cmd: python3 extract-characters/main_run.py ../steles/detected/ ../steles/detected/ kmeans
    deps:
    - extract-characters/load_data.py
    - extract-characters/main_run.py
    params:
    - load.height
    - load.width
    outs:
    - extract-characters/kmeans
  cluster:
    cmd: python3 extract-characters/char_cluster.py 
    deps:
    - extract-characters/kmeans
    - extract-characters/char_cluster.py
    params:
    - cluster.k
    outs:
    - extract-characters/clusters.json
  prepare:
    cmd: python3 extract-characters/main_run.py ../steles/detected/ ../steles/detected/ cycle
    deps:
    - extract-characters/load_data.py
    - extract-characters/main_run.py
    params:
    - prepare.height
    - prepare.width
    outs:
    - extract-characters/cycle
  organise:
    cmd: bash extract-characters/organise.sh /home/jonasd/StrokelessGAN/data/
    deps:
    - extract-characters/organise.sh
    - extract-characters/clusters.json
    - extract-characters/cycle
    outs:
    - data/trainA
    - data/trainB
